// <auto-generated />
using System;
using FolderExplorer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FolderExplorer.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231123202448_PredefinedFoldersDataAdded")]
    partial class PredefinedFoldersDataAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("FolderExplorer.Entities.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentFolderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("Folders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Creating Digital Images"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Resources",
                            ParentFolderId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Evidence",
                            ParentFolderId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Graphic Products",
                            ParentFolderId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Primary Sources",
                            ParentFolderId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Secondary Sources",
                            ParentFolderId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Process",
                            ParentFolderId = 4
                        },
                        new
                        {
                            Id = 8,
                            Name = "Final Product",
                            ParentFolderId = 4
                        });
                });

            modelBuilder.Entity("FolderExplorer.Entities.Folder", b =>
                {
                    b.HasOne("FolderExplorer.Entities.Folder", "ParentFolder")
                        .WithMany("ChildFolders")
                        .HasForeignKey("ParentFolderId");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("FolderExplorer.Entities.Folder", b =>
                {
                    b.Navigation("ChildFolders");
                });
#pragma warning restore 612, 618
        }
    }
}
